name: GitHub Secrets

on:
  workflow_dispatch:



jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "APP_SECRET: ${{ secrets.MY_TOP_SECRET  }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"
            
      - name: Print Secret as an environment variable
        run: |
            echo "APP_SECRET: $MY_TOP_SECRET"
        env:
            MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}
